version: '3.1'

services:
    instapic-db:
        image: postgres:12
        container_name: instapic-db
        ports:
            - 5432:5432
        restart: always
        environment: 
            POSTGRES_PASSWORD: example
            POSTGRES_DB: instapic
            TZ: UTC
            PGTZ: UTC
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - instapic-network

networks:
    instapic-network:
        external: 
            name: instapic